FROM fedora:39

# Install dependencies
RUN dnf -y update && \
    dnf -y install \
        make \
        gcc \
        gcc-c++ \
        cmake \
        git \
        pkg-config \
        SFML-devel && \
    dnf clean all

WORKDIR /app
COPY . .

RUN ./install_vcpkg.sh

# Build the server
RUN rm -rf build && \
    mkdir -p build && \
    cd build && \
    cmake .. && \
    make -j server

# Expose ports (TCP + UDP)
EXPOSE 8081/tcp
EXPOSE 8081/udp

# Run the server
CMD ["./r-type_server"]