# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexiss/delivery/tek3/r-type/mirror_r-type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexiss/delivery/tek3/r-type/mirror_r-type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexiss/delivery/tek3/r-type/mirror_r-type/CMakeFiles /home/alexiss/delivery/tek3/r-type/mirror_r-type//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexiss/delivery/tek3/r-type/mirror_r-type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtype_client

# Build rule for target.
rtype_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_client
.PHONY : rtype_client

# fast build rule for target.
rtype_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/build
.PHONY : rtype_client/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named clean_verbose

# Build rule for target.
clean_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_verbose
.PHONY : clean_verbose

# fast build rule for target.
clean_verbose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_verbose.dir/build.make CMakeFiles/clean_verbose.dir/build
.PHONY : clean_verbose/fast

client/RType.o: client/RType.cpp.o
.PHONY : client/RType.o

# target to build an object file
client/RType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/client/RType.cpp.o
.PHONY : client/RType.cpp.o

client/RType.i: client/RType.cpp.i
.PHONY : client/RType.i

# target to preprocess a source file
client/RType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/client/RType.cpp.i
.PHONY : client/RType.cpp.i

client/RType.s: client/RType.cpp.s
.PHONY : client/RType.s

# target to generate assembly for a file
client/RType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/client/RType.cpp.s
.PHONY : client/RType.cpp.s

game/graphics.o: game/graphics.cpp.o
.PHONY : game/graphics.o

# target to build an object file
game/graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/game/graphics.cpp.o
.PHONY : game/graphics.cpp.o

game/graphics.i: game/graphics.cpp.i
.PHONY : game/graphics.i

# target to preprocess a source file
game/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/game/graphics.cpp.i
.PHONY : game/graphics.cpp.i

game/graphics.s: game/graphics.cpp.s
.PHONY : game/graphics.s

# target to generate assembly for a file
game/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_client.dir/build.make CMakeFiles/rtype_client.dir/game/graphics.cpp.s
.PHONY : game/graphics.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean_verbose"
	@echo "... fclean"
	@echo "... re"
	@echo "... rtype_client"
	@echo "... client/RType.o"
	@echo "... client/RType.i"
	@echo "... client/RType.s"
	@echo "... game/graphics.o"
	@echo "... game/graphics.i"
	@echo "... game/graphics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

