#pragma once

#include "systems/AnimationSystem.hpp"
#include "systems/BackgroundSystem.hpp"
#include "systems/BonusSystem.hpp"
#include "systems/BoundarySystem.hpp"
#include "systems/CollisionSystem.hpp"
#include "systems/EnemySystem.hpp"
#include "systems/GameLogicSystem.hpp"
#include "systems/GravitySystem.hpp"
#include "systems/InputSystem.hpp"
#include "systems/JumpSystem.hpp"
#include "systems/LaserWarningSystem.hpp"
#include "systems/MovementSystem.hpp"
#include "systems/OffscreenCleanupSystem.hpp"
#include "systems/PlayerSystem.hpp"
#include "systems/ProjectileSystem.hpp"
#include "systems/RenderSystem.hpp"
