name: Push to Mirror Repository

env:
  MIRROR_URL: "git@github.com:EpitechPGE3-2025/G-CPP-500-TLS-5-1-rtype-4.git"
  MIRROR_REPO: "EpitechPGE3-2025/G-CPP-500-TLS-5-1-rtype-4"

on:
  workflow_run:
    workflows:
      - "Check C++ Formatting"
    types:
      - completed

jobs:
  push_to_mirror:
    if: github.repository != env.MIRROR_REPO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

